# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-12-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoustip',
            name='stay_in_touch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymoustip',
            name='upload_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
